name: Weave Scope
description: "Monitoring, visualisation and management for Docker"
version: 1.6.7
category: Monitoring
maintainer: "Ilya Dmitrichenko <ilya@weave.works>"
license: "Apache License v2.0"
projectURL: https://github.com/weaveworks/scope
